version: '3.3'

services:
  banca-db:
    container_name: mariadb
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: banca
      MARIADB_USER: root
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
  banca-api:
    container_name: bancaApi
    image: banca-api
    ports:
      - 9091:9091
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/banca
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
    build:
      context: .
      dockerfile: Dockerfile
volumes:
  data: {}
