version: '5'

services:
  banca-db:
    container_name: mariadb
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: banca
      MARIADB_USER: root
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      api_network:
        ipv4_address: 10.5.0.6
  banca-api:
    container_name: bancaApi
    image: banca-api
    ports:
      - '8090:8089'
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/banca
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      api_network:
        ipv4_address: 10.5.0.6
volumes:
  data: {}
networks:
  api_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
